# Generated by Django 2.2.28 on 2023-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vvnnf', models.BigIntegerField()),
                ('etrty', models.BigIntegerField()),
                ('weryy', models.BigIntegerField()),
            ],
        ),
    ]
